spring:
  application:
    name: customer-service
  sql:
    init:
      data-locations: classpath:sql/data.sql
server:
  port: 6060

customer:
  service:
    url:http://localhost:6060
stock:
  service:
    url:http://localhost:7070

#logging:
#  level:
#    io:
#      r2dbc:
#        h2:
#          H2Connection: OFF